// lib/ui/screens/connection_screen.dart
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:provider/provider.dart';
import 'dart:io';
import '../../features/p2p/qr_connection_service.dart';
import '../../features/contacts/contact_service.dart';
import '../../features/contacts/contact_model.dart';
import '../widgets/qr_display_widget.dart';
import '../widgets/qr_scanner_widget.dart';
import '../theme/theme_provider.dart';
import 'chat_screen.dart';
import '../../core/service/connection_manager_service.dart';
import 'package:logger/logger.dart';
import '../../core/models/user_role.dart';
import '../../features/session/session_service.dart';
import '../../core/service/navigation_service.dart';
import '../../core/service/global_error_handler.dart';

// ConnectionMode enum represents different states of the connection process
enum ConnectionMode {
  welcome, // Initial state showing connection options
  initiator, // Generating QR code for others to scan
  receiver, // Scanning QR code generated by others
  connecting, // Establishing connection after QR scan
}

// Screen for establishing P2P connections between users
class ConnectionScreen extends StatefulWidget {
  final String? contactId;
  final String contactName;
  final UserRole userRole; // Added to determine available features

  const ConnectionScreen({
    Key? key,
    this.contactId,
    required this.contactName,
    required this.userRole,
  }) : super(key: key);

  @override
  State<ConnectionScreen> createState() => _ConnectionScreenState();
}

class _ConnectionScreenState extends State<ConnectionScreen> {
  // Screen state variables
  ConnectionMode _mode = ConnectionMode.welcome;
  String? _errorMessage;
  bool _checkingExistingSession = true;
  final _logger = Logger();

  // Phase 1 state tracking
  bool _webrtcWasConnected = false;
  bool _phase1DisconnectDetected = false;
  bool _hasNavigatedToChat = false;

  // Connection info for QR code
  ConnectionInfo? _connectionInfo;

  // Signaling server URL - will be initialized with the proper IP
  late String _signalingServerUrl;

  // Reference to the connection manager
  late ConnectionManagerService _connectionManager;
  Contact? _contact;
  late ContactService _contactService;
  late final SessionService _sessionService;

  @override
  void initState() {
    super.initState();

    _logger.d(
        'SESSION_EXTRA_CREATION: ConnectionScreen.initState called for contact ${widget.contactId}');

    // Set signaling server URL
    _signalingServerUrl = 'ws://192.168.0.214:8080'; // Default as fallback

    // Try to get the actual machine IP for better connection
    _initializeServerUrl();

    // Get the shared connection manager and contact service
    _connectionManager =
        Provider.of<ConnectionManagerService>(context, listen: false);
    _contactService = Provider.of<ContactService>(context, listen: false);
    _sessionService = Provider.of<SessionService>(context, listen: false);
    _connectionManager.initializeServices();

    // Listen for connection state changes (pass bool parameter)
    _connectionManager.addListener(_connectionStateListener);

    // Load contact details and check for existing session
    _loadContactAndCheckSession();
  }

  // Initialize the signaling server URL with the correct IP
  Future<void> _initializeServerUrl() async {
    try {
      // Get network interfaces
      final interfaces = await NetworkInterface.list(
        type: InternetAddressType.IPv4,
        includeLinkLocal: false,
      );

      // Find a suitable interface (non-loopback)
      for (var interface in interfaces) {
        for (var addr in interface.addresses) {
          if (!addr.isLoopback) {
            // Use this IP for the signaling server URL
            _signalingServerUrl = 'ws://${addr.address}:8080';
            _logger.d('Using signaling server URL: $_signalingServerUrl');
            return;
          }
        }
      }

      _logger
          .w('Could not find a suitable network interface, using default URL');
    } catch (e) {
      _logger.e('Error getting network interfaces: $e');
      // Use the default URL as a fallback
    }
  }

  Future<void> _loadContactAndCheckSession() async {
    _logger.d(
        'SESSION_EXTRA_CREATION: ConnectionScreen._loadContactAndCheckSession called for contact ${widget.contactId}');

    setState(() {
      _checkingExistingSession = true;
    });

    try {
      // Load contact details only, don't check for existing session
      _contact = await _contactService.getContact(widget.contactId!);

      _logger.d(
          'SESSION_EXTRA_CREATION: Loaded contact with metadata: ${_contact?.metadata}');

      // Skip the automatic session check - this will always show the welcome screen
      _logger.d(
          'Loaded contact details for ${widget.contactId}, showing welcome screen');
    } catch (e) {
      _logger.e('Error loading contact details: $e');
      setState(() {
        _errorMessage = 'Error loading contact details: $e';
      });
    } finally {
      if (mounted) {
        setState(() {
          _checkingExistingSession = false;
        });
      }
    }
  }

  Future<void> _deleteContact() async {
    final confirmed = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Delete Contact'),
        content: const Text(
            'Are you sure you want to delete this contact? This will also delete all messages and sessions.'),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context, false),
            child: const Text('Cancel'),
          ),
          TextButton(
            onPressed: () => Navigator.pop(context, true),
            child: const Text('Delete'),
            style: TextButton.styleFrom(foregroundColor: Colors.red),
          ),
        ],
      ),
    );

    if (confirmed == true) {
      try {
        // Delete contact
        await _contactService.deleteContact(widget.contactId!);

        // Close any existing connection
        await _connectionManager.closeConnection();

        if (mounted) {
          Navigator.pop(context);
        }
      } catch (e) {
        _logger.e('Error deleting contact: $e');
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error deleting contact: $e')),
        );
      }
    }
  }

  Future<void> _editContact() async {
    final TextEditingController nameController =
        TextEditingController(text: _contact?.name);

    final result = await showDialog<String>(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Edit Contact'),
        content: TextField(
          controller: nameController,
          decoration: const InputDecoration(
            labelText: 'Name',
            hintText: 'Enter contact name',
          ),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('Cancel'),
          ),
          TextButton(
            onPressed: () => Navigator.pop(context, nameController.text),
            child: const Text('Save'),
          ),
        ],
      ),
    );

    if (result != null && result.isNotEmpty && _contact != null) {
      try {
        final updatedContact = _contact!.copyWith(name: result);
        await _contactService.updateContact(updatedContact);

        setState(() {
          _contact = updatedContact;
        });
      } catch (e) {
        _logger.e('Error updating contact: $e');
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error updating contact: $e')),
        );
      }
    }
  }

  // We've removed the complex _checkForExistingSession method
  // Session checks are now handled in the contacts screen with a single reliable method
  // This simplifies the connection screen and prevents race conditions

  // Listener for connection state changes
  Future<void> _connectionStateListener() async {
    // PHASE 1 TEST: Check for WebRTC disconnection but session persistence
    final isQrServiceAvailable = _connectionManager.qrConnectionService != null;
    final isQrServiceConnected = isQrServiceAvailable
        ? _connectionManager.qrConnectionService!.isConnected
        : false;
    final hasActiveSession = _connectionManager.currentSessionId != null;
    final currentMode = _mode;
    final isModeAllowed = (_mode == ConnectionMode.connecting ||
        _mode == ConnectionMode.receiver ||
        _mode == ConnectionMode.initiator);

    print('🔍 [PHASE1 TEST] _connectionStateListener called:');
    print('   - QR Service Available: $isQrServiceAvailable');
    print('   - QR Service Connected: $isQrServiceConnected');
    print('   - Has Active Session: $hasActiveSession');
    print('   - Current Mode: $currentMode');
    print('   - Mode Allowed: $isModeAllowed');
    print('   - WebRTC Was Connected: $_webrtcWasConnected');

    // Track WebRTC connection state changes
    if (isQrServiceConnected && !_webrtcWasConnected) {
      print('PHASE1: WebRTC just connected!');
      _webrtcWasConnected = true;

      // NEW: Always call key exchange on WebRTC connection
      if (hasActiveSession && _connectionManager.qrConnectionService != null) {
        print(
            'KEY-EXCHANGE: Initiating key exchange/validation for session: ${_connectionManager.currentSessionId}');
        _connectionManager.qrConnectionService!.handleConnectionEstablished(
          _connectionManager.currentSessionId!,
          widget.contactId!,
        );
      }
    } else if (!isQrServiceConnected &&
        _webrtcWasConnected &&
        hasActiveSession) {
      print(
          '🔑 [PHASE1 SUCCESS] WebRTC disconnected after connection - Phase 1 complete!');
      _phase1DisconnectDetected = true;
      _webrtcWasConnected = false;
    }

    // Navigation logic - prevent multiple navigation attempts
    if (_hasNavigatedToChat) {
      print('🚫 [DEBUG] Already navigated to chat - ignoring subsequent calls');
      return;
    }

    if (_phase1DisconnectDetected && hasActiveSession && isModeAllowed) {
      print(
          '✅ [PHASE1] Navigating to chat - session paired, WebRTC disconnected');
      _phase1DisconnectDetected = false; // Reset flag
      _hasNavigatedToChat = true; // Prevent multiple navigation
      await _onConnectionStateChanged(true);
    } else if (isQrServiceConnected &&
        isModeAllowed &&
        !_phase1DisconnectDetected) {
      print('✅ [DEBUG] Standard WebRTC connection - navigating to chat');
      _hasNavigatedToChat = true; // Prevent multiple navigation
      await _onConnectionStateChanged(true);
    } else {
      print('❌ [DEBUG] Not navigating - waiting for proper connection flow');
    }
  }

  // Handle connection state changes
  Future<void> _onConnectionStateChanged(bool isConnected) async {
    if (isConnected) {
      // Now the client has connected!
      // Mark session as active, update metadata, and navigate to chat
      if (_connectionManager.currentSessionId != null &&
          widget.contactId != null) {
        GlobalErrorHandler.logInfo(
            'SESSION_LIFECYCLE: Marking session as active',
            data: {
              'session_id': _connectionManager.currentSessionId,
              'contact_id': widget.contactId,
            });

        await _sessionService
            .markSessionActive(_connectionManager.currentSessionId!);

        GlobalErrorHandler.logInfo(
            'SESSION_LIFECYCLE: Updating contact metadata',
            data: {
              'contact_id': widget.contactId,
              'session_id': _connectionManager.currentSessionId,
            });

        await _contactService.updateContactWithSessionInfo(
            widget.contactId!, _connectionManager.currentSessionId!, true);

        GlobalErrorHandler.logInfo(
            'SESSION_LIFECYCLE: Session and contact metadata updated',
            data: {
              'session_id': _connectionManager.currentSessionId,
              'contact_id': widget.contactId,
            });
      }
      NavigationService.navigateToChatScreen(
        context,
        widget.contactId!,
        widget.contactName,
        widget.userRole,
      );
    }
  }

  // Generate connection info and become an initiator
  // Only available to lawyers as per requirements
  Future<void> _becomeInitiator() async {
    // Check if user is a lawyer - only lawyers can generate QR codes
    if (widget.userRole != UserRole.initiator) {
      setState(() {
        _errorMessage = 'Only lawyers can generate QR codes';
      });
      return;
    }

    setState(() {
      _mode = ConnectionMode.initiator;
      _errorMessage = null;
    });

    try {
      _logger.d('Generating QR code connection info');

      // Ensure services are initialized
      if (_connectionManager.qrConnectionService == null) {
        _logger.d('QRConnectionService is null - initializing services');
        await _connectionManager.initializeServices();
        if (_connectionManager.qrConnectionService == null) {
          throw Exception('Failed to initialize QRConnectionService');
        }
      }

      // Generate connection info using the shared service
      final connectionInfo = await _connectionManager.qrConnectionService!
          .generateConnectionInfo(_signalingServerUrl);

      _logger.d(
          'Connection info generated successfully: ${connectionInfo.sessionId}');

      // IMPORTANT: For lawyers, we need to store the session ID in a special way
      // This ensures the session persists for reconnection after navigating away
      if (widget.userRole == UserRole.initiator && widget.contactId != null) {
        // Pre-create a session with the exact ID generated for the QR code
        _logger.d(
            'SESSION_EXTRA_CREATION: About to create session with ID ${connectionInfo.sessionId} for contact ${widget.contactId}');
        await _sessionService.createSessionWithExistingId(
          connectionInfo.sessionId,
          widget.contactId!,
          purgeEnabled: true,
        );

        // CRITICAL: Session key generation is now handled by QRConnectionService
        // using SessionKeyService - no need to generate manually here
        _logger.d(
            'Session ${connectionInfo.sessionId} prepared - key generation will happen during connection');

        // IMPORTANT: We're not marking the session as established yet
        // We're just preparing metadata for when the connection is actually made
        await _contactService.updateContactWithSessionInfo(widget.contactId!,
            connectionInfo.sessionId, false); // Set hasSession to false

        // Set current session in connection manager
        _connectionManager.setCurrentSession(
          sessionId: connectionInfo.sessionId,
          contactId: widget.contactId!,
          contactName: widget.contactName,
        );

        _logger.d(
            'Lawyer session ${connectionInfo.sessionId} prepared - awaiting client connection');
      }

      if (mounted) {
        setState(() {
          _connectionInfo = connectionInfo;
        });
      }
    } catch (e) {
      _logger.e('Error generating connection info: $e');
      if (mounted) {
        setState(() {
          _errorMessage = 'Error generating QR code: $e';
        });
      }
    }
  }

  // Switch to receiver mode to scan QR code
  // Available to both lawyers and clients
  void _becomeReceiver() {
    setState(() {
      _mode = ConnectionMode.receiver;
      _errorMessage = null;
    });
  }

  // Handle QR code scanning
  // Modify _handleQrScanned to include contactId
  Future<void> _handleQrScanned(String qrData) async {
    setState(() {
      _mode = ConnectionMode.connecting;
      _errorMessage = null;
    });

    try {
      // Connect using QR data via the shared service, passing contactId
      final success = await _connectionManager.qrConnectionService!
          .connectUsingQrInfo(qrData, widget.contactId!);

      if (success) {
        // Extract connection info from QR data to set session ID
        final connectionInfo = ConnectionInfo.fromQrString(qrData);

        // Set the current session in the manager
        _connectionManager.setCurrentSession(
          sessionId: connectionInfo.sessionId,
          contactId: widget.contactId!,
          contactName: widget.contactName,
        );
      } else {
        setState(() {
          _errorMessage = 'Failed to connect using QR code';
          _mode = ConnectionMode.welcome;
        });
      }
    } catch (e) {
      setState(() {
        _errorMessage = 'Error connecting: $e';
        _mode = ConnectionMode.welcome;
      });
    }
  }

  // This method is no longer needed as we've simplified the connection flow
  // Connection handling is now done in the contacts screen

  // Cancel connection attempt and return to welcome mode
  void _cancelConnection() {
    _connectionManager.closeConnection();

    setState(() {
      _mode = ConnectionMode.welcome;
      _errorMessage = null;
      _connectionInfo = null;
    });
  }

  @override
  void dispose() {
    // Remove listener but DON'T dispose the connection
    _connectionManager.removeListener(_connectionStateListener);
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(_contact?.name ?? widget.contactName),
        actions: [
          IconButton(
            icon: const Icon(Icons.edit),
            onPressed: _editContact,
          ),
          IconButton(
            icon: const Icon(Icons.delete),
            onPressed: _deleteContact,
          ),
        ],
      ),
      body: _checkingExistingSession
          ? const Center(child: CircularProgressIndicator())
          : _errorMessage != null
              ? Center(
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      Text(
                        _errorMessage!,
                        style: const TextStyle(color: Colors.red),
                        textAlign: TextAlign.center,
                      ),
                      const SizedBox(height: 16),
                      ElevatedButton(
                        onPressed: () {
                          setState(() {
                            _errorMessage = null;
                            _mode = ConnectionMode.welcome;
                          });
                        },
                        child: const Text('Try Again'),
                      ),
                    ],
                  ),
                )
              : _buildConnectionContent(),
    );
  }

  Widget _buildConnectionContent() {
    switch (_mode) {
      case ConnectionMode.welcome:
        return _buildWelcomeScreen();
      case ConnectionMode.initiator:
        return _buildInitiatorScreen();
      case ConnectionMode.receiver:
        return _buildReceiverScreen();
      case ConnectionMode.connecting:
        return _buildConnectingScreen();
    }
  }

  Widget _buildWelcomeScreen() {
    final themeProvider = Provider.of<ThemeProvider>(context);
    return SafeArea(
      child: Center(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Icon(
                Icons.wifi_tethering,
                size: 64,
                color: themeProvider.isDarkMode
                    ? AppColors.secondary
                    : AppColors.primary,
              ),
              const SizedBox(height: 24),
              Text(
                'Secure Connection',
                style: GoogleFonts.inter(
                  fontSize: 24,
                  fontWeight: FontWeight.bold,
                ),
              ),
              const SizedBox(height: 8),
              Text(
                'Choose how you want to connect to ${widget.contactName}',
                textAlign: TextAlign.center,
                style: GoogleFonts.inter(
                  fontSize: 16,
                ),
              ),
              const SizedBox(height: 32),

              // Role-specific options
              // Only lawyers can generate QR codes
              if (widget.userRole == UserRole.initiator) ...[
                ElevatedButton(
                  onPressed: _becomeInitiator,
                  style: ElevatedButton.styleFrom(
                    padding: const EdgeInsets.symmetric(
                        horizontal: 32, vertical: 16),
                  ),
                  child: Text(
                    'Generate QR Code',
                    style: GoogleFonts.inter(
                      fontSize: 16,
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
                const SizedBox(height: 16),
              ],

              // Both roles can scan QR codes
              OutlinedButton(
                onPressed: _becomeReceiver,
                style: OutlinedButton.styleFrom(
                  padding:
                      const EdgeInsets.symmetric(horizontal: 32, vertical: 16),
                ),
                child: Text(
                  'Scan QR Code',
                  style: GoogleFonts.inter(
                    fontSize: 16,
                    fontWeight: FontWeight.w500,
                  ),
                ),
              ),

              const SizedBox(height: 32),
              Divider(),
              const SizedBox(height: 16),
              Text(
                'Secure, Private, Anonymous',
                style: GoogleFonts.inter(
                  fontWeight: FontWeight.bold,
                ),
              ),
              const SizedBox(height: 8),
              Text(
                'All communication is end-to-end encrypted with no persistent identifiers.',
                textAlign: TextAlign.center,
                style: GoogleFonts.inter(
                  fontSize: 14,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildInitiatorScreen() {
    return SafeArea(
      child: Center(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(16.0),
          child: _connectionInfo == null
              ? Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    const CircularProgressIndicator(),
                    const SizedBox(height: 16),
                    Text(
                      'Generating QR code...',
                      style: GoogleFonts.inter(
                        fontSize: 16,
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                    const SizedBox(height: 16),
                    TextButton(
                      onPressed: _cancelConnection,
                      child: Text(
                        'Cancel',
                        style: GoogleFonts.inter(
                          color: Colors.red,
                        ),
                      ),
                    ),
                  ],
                )
              : Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    QRDisplayWidget(
                      connectionInfo: _connectionInfo!,
                      onCancelPressed: _cancelConnection,
                    ),
                  ],
                ),
        ),
      ),
    );
  }

  Widget _buildReceiverScreen() {
    return SafeArea(
      child: Center(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              QRScannerWidget(
                onQrScanned: _handleQrScanned,
                onCancelPressed: _cancelConnection,
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildConnectingScreen() {
    return SafeArea(
      child: Center(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              const CircularProgressIndicator(),
              const SizedBox(height: 16),
              Text(
                'Establishing secure connection...',
                style: GoogleFonts.inter(
                  fontSize: 16,
                  fontWeight: FontWeight.w500,
                ),
              ),
              const SizedBox(height: 8),
              Text(
                'This may take a moment',
                style: GoogleFonts.inter(
                  fontSize: 14,
                ),
              ),
              const SizedBox(height: 16),
              TextButton(
                onPressed: _cancelConnection,
                child: Text(
                  'Cancel',
                  style: GoogleFonts.inter(
                    color: Colors.red,
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
